config/routes.rb
Jobboard::Application.routes.draw do
  resources :jobs
  resources :groups

  match '/auth/:provider/callback', to: 'sessions#create', as: 'login'
  match '/logout', to: 'sessions#destroy', as: 'logout'

  root :to => 'jobs#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :title, :user_id
  has_many :memberships
  has_many :members, :through => :memberships
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :cost, :description, :title
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :member_id, :user_id
  belongs_to :user
  has_many :member, :class_name => 'User'
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  attr_accessible :email, :icon_url, :name, :nickname, :provider, :uid,
                  :token, :secret

  # relations
  has_many :jobs # 依頼主として
  has_many :groups # グループ作成主として
  has_many :memberships
  has_many :my_groups, :through => :memberships # 自分の所属するグループ
  has_many :my_jobs, :through => :my_groups # 自分が見られる仕事

  def self.find_or_create_by_auth_hash(auth)
    user = User.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
    user.update_attributes(
      name: auth['info']['name'],
      nickname: auth['info']['nickname'],
      icon_url: auth['info']['image'],
      email: auth['info']['email'],
      token: auth['credentials']['token'],
      secret: auth['credentials']['secret']
    )
    user
  end

  def friends
    uids = fb_friends.map(&:identifier)
    User.where('uid in (?)', uids).all
  end

  private
  def fb_user
    FbGraph::User.fetch(nickname, :access_token => token)
  end

  def fb_friends
    fb_user.friends
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :logged_in?

  private
  def require_login
    redirect_to '/auth/facebook' unless logged_in?
  end
  def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end
  def logged_in?
    session[:user_id].present?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :require_login

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.groups.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = current_user.groups.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = current_user.groups.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = current_user.groups.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = current_user.groups.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :require_login
  
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_by_auth_hash(auth_hash)
    if user.present?
      session[:user_id] = user.id
    end
    redirect_to :root
  end

  def destroy
    session.clear
    redirect_to :root
  end

  private
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  -if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    %ul
    -current_user.send(:fb_friends).each do |friend|
      %li
        = fields_for "group[members]", friend, :index => nil do |form|
          = form.check_box :identifier, {checked: false}, friend.identifier
        = friend.name
  .actions
    = f.submit 'Save'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Listing groups

%table
  %tr
    %th
    %th
    %th

  - @groups.each do |group|
    %tr
      %td= group.title
      %td= link_to 'Show', group
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path

app/views/jobs/_form.html.haml
= form_for @job do |f|
  -if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :cost
    = f.number_field :cost
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
%h1 Listing jobs

%table
  %tr
    %th Title
    %th Cost
    %th Description
    %th
    %th
    %th

  - @jobs.each do |job|
    %tr
      %td= job.title
      %td= job.cost
      %td= job.description
      %td= link_to 'Show', job
      %td= link_to 'Edit', edit_job_path(job)
      %td= link_to 'Destroy', job, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Job', new_job_path

app/views/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to 'Back', jobs_path

app/views/jobs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @job.title
%p
  %b Cost:
  = @job.cost
%p
  %b Description:
  = @job.description

= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "application/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "text/css", "http-equiv" => "Content-Style-Type"}/
    %meta{:content => "text/javascript", "http-equiv" => "Content-Script-Type"}/
    /[if lt IE 9]
      %script{:src => "http://html5shiv.googlecode.com/svn/trunk/html5.js"}
      %script{:src => "#{@theme.path}/javascripts/PIE.js"}
  %body
    %header#header
      .inner
        .title
          %h1 aaaaaa
    #wrap
      #main
        = yield
      %aside#sub
        .tags
          %h1 Tags
          %ul
      %footer#footer
        .copyright
          Copyright©
          %a{:href => "/"}
            aaaaa
          All Rights Reserved
        .poweredby
          powered by
          aaaa